### PR TITLE
Make spinner colorful and smoother

### PR DESCRIPTION
**Pull request by Gowee**
Before: ◐◓◑◒
Now: 🌕🌖🌗🌘🌑🌒🌓🌔

EpRSEAKiR6

The new spinner is smoother and colorful!

~~As an alternative, here is a more delightful spinner:~~

sxrtaSky6u

~~`const spinner = "😕 😟 🙁 😮 😯 😲 😳 🥺 😦 😧 😨 😰 😥 😢 😭 😱 😖 😣 😞".split(" "); //☹`~~

XD

### CODE REVIEW

**Comment by Xanewok** [comment]
Thanks, that indeed looks better :)

**Comment by BO41** [comment]
Nice idea, but it does not seem to work everywhere.

moon

**Comment by Gowee** [comment]
@BO41 I suppose that it can be fixed by installing & configuring an emoji font. But it also suggests that the new spinner might not work out of the box. So I am afraid it is better to revert to the old one. What regret 🙁.

**Comment by p-avital** [comment]
Or we could go overkill and have a setting for that 😃

**Comment by BO41** [comment]
Shouldn't the status bar use the same font for all vscode installations?
Is there a way to check if the moons are supported on the installed font?
A separate setting is really kinda overkill

**Comment by Xanewok** [comment]
Fixed in #771, will be using octicon font included in the vscode installation. Sorry about regression!

**Pull request merged**
