### PR TITLE
Clean up (part 3)

### PR DESCRIPTION
**Pull request by Xanewok**
Things left to do:
- Finish moving setup (installing toolchain etc.) to task-based workflow (UX is a lot better)
- Separate LSP/toolchain setup to different files

### CODE REVIEW

**Comment by Xanewok** [comment]
@yisonPylkita if possible, could I ask you to test if WSL still works as expected with this merged change? I was extra careful not to mess anything but something might've slipped by - I'd love to catch that before releasing a new version. I'd be much obliged!

**Comment by yisonPylkita** [comment]
Wow, That was quite a refactor!
I will check `master` branch tomorrow on WSL

**Comment by yisonPylkita** [comment]
I did some tests on `master` and it looks good (beside `rls` still missing in lastest nightly)

**Comment by Xanewok** [comment]
Awesome, thank you for that!

**Pull request merged**
