### PR TITLE
Add start and stop commands for rls, add auto start rls config value

### PR DESCRIPTION
**Pull request by Yarn**
Addresses #340 
Adds "Stop the RLS" and "Start the RLS" commands.
Adds `rust.autoStartRls` setting.

`rust.autoStartRls` defaults to `true` keeping current behavior. If set to `false` opening files or adding projects to the workspace will not result in the RLS starting.

The existing auto-start behavior only triggered once per project until the extension is reloaded. As a result stopping the RLS will result in it staying stopped for a project until vscode is restarted/reloaded.

The start command can be used to start the RLS after it is stopped or if auto-start is disabled.

### CODE REVIEW

**Comment by Yarn** [comment]
I'm still getting errors for `Error: command 'rls.update' already exists` in some cases (with `"rust-client.enableMultiProjectSetup": true,`). This stops RLS from being started.

With this change you can trivially trigger the bug by stopping RLS for a project where it is started then starting RLS in any other project (manually or not).
On master it required removing a project from the workspace then performing an action that would result in RLS being started.

The issue is that in `ClientWorkspace.stop` `commandsRegistered` is set to `false` but `this.disposables.forEach(d => d.dispose());` doesn't seem to be sufficient to allow `commands.registerCommand('rls.restart'...` to be called again without an error.

We can work around that by not setting `commandsRegistered` to `false` in `stop` if `rust-client.enableMultiProjectSetup` is set to `true`. I'll wait for confirmation if that's desired or should be part of a separate PR/have a less hacky solution.

**Comment by rivy** [comment]
* fixes #340

**Comment by Xanewok** [comment]
That's a great option and I'd love if we had that =) Do you think you could rebase this PR on top of the current master? Since this PR we've made some changes to command registration and multi-root handling, so hopefully it'll be a lot easier to apply now.

Commands are now registered globally but their behaviour alters depending on the `activeWorkspace`:
https://github.com/rust-lang/rls-vscode/blob/30b399dae0dde617af5c67b5cbe858079311ae07/src/extension.ts#L439-L454

**Comment by Yarn** [comment]
Merge complete. I changed the setting to `rust-client.autoStartRls` since `rust.*` settings apparently get passed (sort of) directly to RLS.

**Pull request closed without merging**
